### PR TITLE
Use Semantic

### PR DESCRIPTION
**Pull request by MilkGames**
- [x] Use Semantic's table (with actions)

- [ ] Update settings UI

- [x] Update login UI

### CODE REVIEW

**Comment by MilkGames** [comment]
image

**Comment by MilkGames** [comment]
Or something like 
image

**Comment by RockyGhostx** [comment]
This
https://user-images.githubusercontent.com/10010026/60932204-2d0f3200-a2bd-11e9-80bf-04106c05b4f0.png

**Comment by RockyGhostx** [comment]
This
60932204-2d0f3200-a2bd-11e9-80bf-04106c05b4f0 (1)

**Comment by MilkGames** [comment]
Settled for 
image

Now: Should yes/no dialogs be native or should they be a Semantic modal?

**Pull request closed without merging**
